name = "idkaboutbytes/subscription"
version = "1.0.0"
description = "Subscription package for Roblox."
license = "MIT"
authors = ["idkaboutbytes"]
repository = "https://github.com/idkaboutbytes/subscription"
includes = [
    "pesde.toml",
    "README.md",
    "CHANGELOG.md",
    "default.project.json",
    "src/**/*.luau",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
MaidTaskUtils = { repo = "idkaboutbytes/maidtaskutils", rev = "v1.0.0" }
